name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIAZAR4WJ52C3BSV4VY }}
          aws-secret-access-key: ${{ Fz8+jov9ltBmpu8Ussfu6eeICus86rNpAQ5vxyAV }}
          aws-region: ap-south-1

      - name: Deploy to AWS
        run: |
          # Your AWS deployment commands go here
          aws s3 sync ./Github workflow s3://man432


